import type { ExperienceEntry } from "@/app/types";

export const experience: ExperienceEntry[] = [
  {
    key: "elsight-simjung",
    role: "Senior Python Developer",
    company: "Elsight Ltd.",
    companyUrl: "https://www.elsight.com",
    companyLogoKey: "simjung",
    outsourcedVia: "Simjung Pvt. Ltd. (Kathmandu, Nepal)",
    outsourcerUrl: "https://simjung.com.np/",
    location: "Tel Aviv, Israel (Remote)",
    period: { start: "2025-11", end: null },
    summary:
      "Feature Lead for a GPS-denied / GPS-spoofed drone positioning system — a new paid feature on Elsight's Halo drone connectivity platform.",
    featureLead: "GPS-Denied / GPS-Spoofed Drone Positioning System",
    highlights: [
      "Leading backend development of a cellular-signal positioning system for drones operating in GPS-degraded and GPS-spoofed environments, processing real-time telemetry at 1 Hz from multi-cellular modem links.",
      "Designed and implemented a modular multi-tier positioning pipeline with automatic strategy selection based on available signal sources — pure Python, zero external dependencies.",
      "Engineered an inertial state-estimator module that fuses positioning estimates with motion telemetry to sustain accuracy when primary positioning is unavailable.",
      "Built a signal-integrity pre-filter that classifies incoming positioning fixes across trust tiers before downstream sensor fusion.",
      "Developed a synthetic mission-data generator to simulate degraded and spoofed flight scenarios and drive accuracy benchmarking across every positioning mode.",
      "Delivered comprehensive automated test coverage using Behave BDD, Playwright E2E, and unit tests — improving release confidence and reducing regression incidents.",
      "Delivered features within 2-week Agile sprints; collaborating cross-functionally on planning, standups, and retrospectives.",
    ],
    techStack: [
      "Python",
      "asyncio",
      "Pandas",
      "GeoPandas",
      "MAVLink",
      "Behave BDD",
      "Playwright",
      "Docker",
      "Linux",
    ],
  },
  {
    key: "elsight-kimbutech",
    role: "Senior Python Developer",
    company: "Elsight Ltd.",
    companyUrl: "https://www.elsight.com",
    companyLogoKey: "kimbutech",
    outsourcedVia: "KimbuTech Pvt. Ltd. (Kathmandu, Nepal)",
    outsourcerUrl: "https://www.kimbutech.com/",
    location: "Tel Aviv, Israel (Remote)",
    period: { start: "2023-08", end: "2025-11" },
    summary:
      "Sole architect of HeatSight — Elsight's premium cellular RF signal-analytics product — plus performance engineering, embedded integration, and observability across the Halo platform.",
    featureLead: "HeatSight — Geospatial RF Signal Analytics",
    highlights: [
      "Solely architected and delivered HeatSight, mapping real-time radio frequency coverage across latitude, longitude, and altitude for ~50 enterprise customers across the USA and Middle East; integrated into the AllSight drone management platform.",
      "Produced full HLD and LLD architecture documents; led technical integration with Israeli frontend firm Elicon as sole technical interface through complete feature delivery.",
      "Diagnosed a systemic bottleneck on Elsight's Halo embedded XMLRPC server (single-threaded, queueing critical APIs behind 3-second connectivity-check polls, triggering Nginx timeouts >60s).",
      "Redesigned with multi-threaded XMLRPC and targeted query optimisation — API response times reduced from >60,000 ms to 600–700 ms (~90% improvement); open-sourced the generalised solution as xmlrpc-extended on PyPI.",
      "Designed and deployed MQTT-based (EMQX) secure telemetry transport between Halo hardware devices and cloud; integrated AT commands for embedded modem configuration and telemetry extraction.",
      "Built BIST (Built-In Self-Test) diagnostic routines for the Beryl embedded device using Linux networking utilities (traceroute, ping, kernel module inspection).",
      "Engineered a Google Authenticator 2FA system reducing authentication costs 40% vs. Okta MFA, with user-lockout controls to defend against brute-force attacks.",
      "Established Prometheus + Grafana observability across microservices for real-time system health visibility and proactive incident detection.",
      "Designed an agentic AI workflow for automated E2E Playwright test generation using LLMs; pioneered GitHub Copilot agentic-coding handoff to accelerate feature delivery and peer review.",
    ],
    techStack: [
      "Python",
      "FastAPI",
      "XMLRPC",
      "MQTT (EMQX)",
      "AT Commands",
      "Pandas",
      "GeoPandas",
      "Prometheus",
      "Grafana",
      "Docker",
      "Kubernetes",
      "Playwright",
      "Linux",
    ],
  },
  {
    key: "nimble-cr",
    role: "Software Engineer",
    company: "Nimble Clinical Research",
    companyUrl: "https://nimble-cr.com",
    companyLogoKey: "nimble-cr",
    outsourcedVia: "Numeric Minds Pvt. Ltd. (Kathmandu, Nepal)",
    location: "New Jersey, USA (Remote)",
    period: { start: "2022-09", end: "2023-08" },
    summary:
      "Built backend services for a cutting-edge clinical-trial analytics platform for pharmaceutical and biotech customers.",
    highlights: [
      "Built a FastAPI service integrating with a tenant-isolated R analytics backend for SDTM/ADaM clinical trial dataset filtering and patient profile report generation.",
      "Engineered Kubernetes pod orchestration to spin R backend pods on-demand per tenant for data isolation and elastic resource management; automated idle pod teardown via Celery scheduled tasks.",
      "Benchmarked duckdb vs. pandas for large clinical dataset subset queries and implemented the winning approach in production.",
      "Implemented TOTP 2FA for the Django admin portal and authored comprehensive unit + Behave BDD test suites.",
      "Managed report storage on Azure Blob and R library storage on Azure File Share.",
    ],
    techStack: [
      "Python",
      "FastAPI",
      "Django",
      "Celery",
      "Kubernetes",
      "duckdb",
      "pandas",
      "Behave BDD",
      "Azure Blob",
      "MongoDB",
    ],
  },
  {
    key: "numeric-minds",
    role: "Python Developer",
    company: "Numeric Minds Pvt. Ltd.",
    companyUrl: "https://www.numericmind.com",
    companyLogoKey: "numeric_minds",
    location: "Kathmandu, Nepal",
    period: { start: "2021-10", end: "2022-09" },
    summary:
      "Full-stack development for a PyQt clinical trial analytics desktop application and its supporting web tools, following CDISC standards.",
    highlights: [
      "Developed Report Designer (low-code TFL — Table/Listing/Figure — report generation) end-to-end across Django REST API and React / Redux / Ant Design frontend.",
      "Developed Template Designer, a dynamic form builder for creating custom clinical report templates.",
      "Created an RTF → PDF/DOC conversion utility with automated table-of-contents generation, used across the clinical reporting pipeline.",
      "Contributed to initial repository setup and CI configuration for both codebases.",
      "Mentored junior developers and conducted technical interviews.",
    ],
    techStack: [
      "Python",
      "Django",
      "Django REST Framework",
      "PyQt",
      "React",
      "Redux",
      "Ant Design",
      "PostgreSQL",
    ],
  },
];
