import type { SkillGroup } from "@/app/types";

export const skillGroups: SkillGroup[] = [
  {
    key: "core-language",
    title: "Core Languages",
    icon: "Code2",
    skills: ["Python", "JavaScript", "TypeScript", "C++"],
  },
  {
    key: "python-ecosystem",
    title: "Python Ecosystem",
    icon: "Boxes",
    skills: [
      "FastAPI",
      "Flask",
      "Django",
      "Celery",
      "asyncio / ASGI",
      "pytest",
      "Behave BDD",
      "Pandas",
      "NumPy",
      "Cython",
    ],
  },
  {
    key: "frontend",
    title: "Frontend",
    icon: "Layout",
    skills: [
      "ReactJs",
      "Redux",
      "Ant Design",
      "shadcn/ui",
      "React Email",
      "HTML5",
      "CSS3",
    ],
  },
  {
    key: "protocols-embedded",
    title: "Protocols & Embedded",
    icon: "Radio",
    skills: [
      "MQTT (EMQX, Mosquitto, NanoMQ)",
      "XMLRPC",
      "AT Commands",
      "MAVLink",
      "Remote ID",
      "QGroundControl",
      "RabbitMQ",
      "ActiveMQ",
    ],
  },
  {
    key: "databases",
    title: "Databases & Cache",
    icon: "Database",
    skills: ["MongoDB", "PostgreSQL", "MySQL", "Redis"],
  },
  {
    key: "cloud-devops",
    title: "Cloud & DevOps",
    icon: "Cloud",
    skills: [
      "AWS (Lambda, EC2, S3, EventBridge, SQS)",
      "Azure",
      "Docker",
      "Kubernetes",
      "Ansible",
      "PyInfra",
    ],
  },
  {
    key: "observability",
    title: "Observability",
    icon: "Activity",
    skills: ["Prometheus", "Grafana"],
  },
  {
    key: "ai-tooling",
    title: "AI & Tooling",
    icon: "Sparkles",
    skills: [
      "Agentic Coding (GitHub Copilot)",
      "Playwright AI E2E",
      "PyTorch",
      "Hugging Face",
    ],
  },
  {
    key: "os-workflow",
    title: "OS & Workflow",
    icon: "Terminal",
    skills: [
      "Linux (Ubuntu)",
      "Git",
      "GitHub",
      "Jira",
      "Confluence",
      "Agile / Scrum",
    ],
  },
];
